[phases.setup]
nixPkgs = [
    "php83", 
    "php83Extensions.pdo", 
    "php83Extensions.pdo_mysql", 
    "php83Extensions.mbstring", 
    "php83Extensions.xml", 
    "php83Extensions.curl", 
    "php83Extensions.zip", 
    "composer"
]

[phases.build]
cmds = ["composer install --no-dev --optimize-autoloader"]

[start]
# On utilise une commande qui ne fait pas crash le serveur si la migration échoue
cmd = "php artisan migrate --force || true && php -S 0.0.0.0:${PORT} -t public/"